### ISSUE TITLE
Landing code on master should not produce a new image

### ISSUE THREAD

**Issue by armenzg** [getsentry/action-release#102]
Currently, almost any code landing on `master` will produce a new Docker image tagged as `latest` which all users of the action will immediately start using.

We need to have control as to when releases happen.

We should only release on tag changes as suggested by @asottile-sentry 

As you can see, the commits below are not code changing, thus, it should not produce a new image

<img width="755" alt="image" src="https://user-images.githubusercontent.com/44410/181625274-d71a9bc0-de9c-4f64-86fc-11e0acd9a28d.png">

<img width="649" alt="image" src="https://user-images.githubusercontent.com/44410/181628374-b9a8140f-9cad-482b-aeda-280e23d56b06.png">

As a side note, to my surprise, the caching gets invalidated with [COPY package.json yarn.lock /action-release](https://github.com/getsentry/action-release/blob/833e51115f17013ed39cb4e1d1e8c072dfcb7f55/Dockerfile#L16) :
https://github.com/getsentry/action-release/runs/7567494647?check_suite_focus=true#step:4:51
Before, [we used to copy it](https://github.com/getsentry/action-release/commit/843e82b6a904fad998a5d5f5d6880e3079cd4edd#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L10-L11) from the builder image.

**Comment by bc-sentry** [comment]
@armenzg Please confirm, but I believe this issue was resolved with the Sentry GoCD deployment pipeline.

**Comment by asottile-sentry** [comment]
that doesn't make sense: there's no gocd pipeline for this repo

**Comment by armenzg** [comment]
As Anthony mentions, it does not apply here. This issue is still valid.

**Comment by bc-sentry** [comment]
Thanks.  I was thinking this was referring to code in other repos that would be released by this action, not the update to this action itself.  Do we have any other GHA repos that have this controlled release suggested (ie. We should only release on tag changes)?  Has lack of this control created pain in the past 2+ years (ie. should we prioritize doing this work)?

**Comment by armenzg** [comment]
It has not caused pain.
It's more of the ideal release process.

The web SDK is also looking to maintain this repo.

Perhaps we wait for them to prioritize the work and let them ask for support where needed.

**Comment by andreiborza** [comment]
This has been reworked. Master will now always get the `master` tag put back into the `action.yml` and the master docker image will be updated.

Git version tags now have docker tags corresponding to the exact version, i.e. 

- git tag v1.2.3 -> docker tag 1.2.3
- git tag v1.2 -> docker tag 1.2.3
- git tag v1 -> docker tag 1.2.3
